Resources:
  DataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: bucket-data-sagemaker-autopilot
  SageMakerDomain:
    Type: AWS::SageMaker::Domain
    DependsOn: DataBucket
    Properties: 
      AuthMode: IAM
      DefaultUserSettings: 
        ExecutionRole: <ROLE ANDA>
      DomainName: DomainSatu
      VpcId: <VPC-ANDA>
      SubnetIds: 
        - <SUBNET-ANDA>
  HerleySageMakerUser:
    Type: AWS::SageMaker::UserProfile
    Properties: 
      DomainId: !GetAtt SageMakerDomain.DomainId
      UserProfileName: herley
Outputs:
  SageMakerDomainID:
    Value: !GetAtt
      - SageMakerDomain
      - DomainId
  SageMakerDomainARN:
    Value: !GetAtt
      - SageMakerDomain
      - DomainArn